global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'simple-rag-project'
    scrape_interval: 5s
    static_configs:
      - targets: ['simple-rag-project:8080']

  - job_name: 'node-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'node-exporter:9100' ]