services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant-local
    ports:
      # Порт для gRPC API
      - "6333:6333"
      # Порт для REST API та веб-інтерфейсу
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data: