apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
#    url: http://clickhouse:8123
    jsonData:
      defaultDatabase: default
      server: clickhouse
      port: 8123
      protocol: http
      username: default
    secureJsonData:
      password: ""
    version: 1
    editable: true